### ISSUE TITLE
gnutella2 module build: `Error: This expression has type string but an expression was expected of type bytes`

### ISSUE THREAD

**Issue by barracuda156** [ygrek/mldonkey#108] opened 2024-08-15 22:57 UTC
I have seen that it is listed as unmaintained, but perhaps it is useful to track what specifically fails.

```
ocamlc -w +a-3-4-6-27-29-32-35-37-41-44-45-48-60-70   -I src/utils/extlib  -I src/utils/cdk  -I src/utils/bitstring  -I src/utils/lib  -I src/utils/ocamlrss  -I src/utils/xml-light  -I src/utils/net  -I tools  -I src/daemon/common  -I src/daemon/driver  -I src/utils/mp3tagui  -I src/config/unix  -I src/gtk2/gui  -I src/gtk2/gui/x11  -I src/gtk2/gui/win32  -I icons/rsvg  -I +lablgtk2  -I src/networks/direct_connect  -I src/networks/gnutella2  -I src/networks/fasttrack  -I src/networks/fileTP  -I src/networks/bittorrent  -I src/networks/donkey -I +camlp4 -I /opt/local/lib/ocaml/site-lib/num -c src/networks/gnutella2/g2Proto.ml
File "src/networks/gnutella2/g2Proto.ml", line 925, characters 11-12:
925 |           (s, ip, port, !udp_counter, 0, last_time () + 10, ref false);
                 ^
Error: This expression has type string but an expression was expected of type
         bytes
gmake: *** [Makefile:5447: src/networks/gnutella2/g2Proto.cmo] Error 2
```

**Comment by chusopr** [comment] 2024-10-20 14:43
I'm able to reproduce it. It looks like #46 was not fixed everywhere.

As you mention, Gnutella and Gnutella2 protocols have been marked as unmaintained since 2007: https://github.com/ygrek/mldonkey/blob/master/docs/ChangeLog.old#L221

So I don't know how likely it is that it will be fixed, although other safe string issues in the Gnutella implementation were fixed by #99

**Comment by carlonluca** [comment] 2024-10-20 15:08
My patches also fixed gnutella and gnutella2 if you want: https://github.com/carlonluca/mldonkey. However, I never tested it.

**Comment by chusopr** [comment] 2024-10-20 15:12
Thanks, @carlonluca. I was about to check your repo for that.
But I wonder how much activity does Gnutella still have.
And FastTrack? Does it still exist? MLDonkey still has the FastTrack plugin, but I don't know if it is of any use nowadays.

**Comment by carlonluca** [comment] 2024-10-20 15:17
If you want, the docker image I uploaded to docker hub is built with gnutella and gnutella2.

Unfortunately I cannot provide answers to your questions, I've never used any of those protocols.

**Comment by chusopr** [comment] 2024-10-20 15:25
Yes, I saw your docker images and your mldonkey-next project which looks quite interesting, but my main work on this is [packaging it for Gentoo](https://packages.gentoo.org/packages/net-p2p/mldonkey/bugs), for which a Docker image wouldn't be appropriate.

**Comment by ygrek** [comment] 2024-11-25 00:37
> As of my last update in August 2023, the Gnutella network is still operational, although it has significantly declined in popularity compared to its peak in the early 2000s. Gnutella is a peer-to-peer file-sharing protocol that allows users to share files directly between their computers without a central server. While it may not be as widely used as other file-sharing networks today, there are still clients and users who utilize the Gnutella network for sharing files.

apparently it is still alive
i wonder if there are any mldonkey users who use it though

**Closed** 2024-11-25 00:39 UTC
