### ISSUE TITLE
fails to build with ocaml 4.07.0

### ISSUE THREAD

**Issue by rosset** [ygrek/mldonkey#31] opened 2018-09-18 21:24 UTC
Full logs here: https://paste.fedoraproject.org/paste/ahWpRANev9srxMXqwrRpIA

+ make depend
make[1]: Entering directory '/home/filiperosset/rpmbuild/my/mldonkey/mldonkey-3.1.6'
/usr/bin/ocamlc.opt -w -3   -I src/utils/extlib  -I src/utils/cdk  -I src/utils/bitstring  -I src/utils/lib  -I src/utils/ocamlrss  -I src/utils/xml-light  -I src/utils/net  -I tools  -I src/daemon/common  -I src/daemon/driver  -I src/utils/mp3tagui  -I src/config/unix  -I src/gtk2/gui  -I src/gtk2/gui/x11  -I src/gtk2/gui/win32  -I icons/rsvg  -I +lablgtk2  -I src/networks/direct_connect  -I src/networks/fasttrack  -I src/networks/fileTP  -I src/networks/bittorrent  -I src/networks/donkey -I +camlp4 -c src/utils/extlib/IO.ml
File "src/utils/extlib/IO.ml", line 70, characters 22-23:
Error: This expression has type bytes but an expression was expected of type
         string
make[1]: *** [Makefile:5447: src/utils/extlib/IO.cmo] Error 2
make[1]: Leaving directory '/home/filiperosset/rpmbuild/my/mldonkey/mldonkey-3.1.6'
make: *** [Makefile:5165: depend] Error 2

**Comment by ygrek** [comment] 2018-09-19 01:46
I believe it is a duplicate of #25

**Closed by ygrek** 2018-09-19 01:46 UTC
